package tech.kayys.wayang.agent.shaker;

import java.io.IOException;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.*;
import java.util.jar.Attributes;
import java.util.jar.JarOutputStream;
import java.util.jar.Manifest;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;

/**
 * Generates minimal standalone agent JARs by tree-shaking unused components.
 *
 * <p>
 * This packager analyzes workflow definitions to determine which components
 * are actually needed, then generates a minimal JAR containing only those
 * components plus their dependencies.
 * </p>
 *
 * <h3>Usage:</h3>
 * <pre>{@code
 * AgentPackager packager = new AgentPackager();
 * Path jarPath = packager.packageAgent(
 *     Path.of("workflow.yaml"),
 *     Path.of("output/agent.jar"),
 *     PackageConfig.builder()
 *         .mainClass("tech.kayys.wayang.agent.core.core.AgentClient")
 *         .optimize(true)
 *         .build()
 * );
 * }</pre>
 *
 * <h3>Generated JAR Structure:</h3>
 * <pre>
 * agent.jar
 * ├── META-INF/MANIFEST.MF
 * │   Main-Class: tech.kayys.wayang.agent.core.core.AgentClient
 * ├── tech/kayys/gollek/agent/core/AgentClient.class
 * ├── tech/kayys/gollek/agent/orchestrator/ReActOrchestrator.class
 * ├── tech/kayys/gollek/agent/tools/*.class (only tools used by workflow)
 * ├── tech/kayys/gollek/agent/skills/*.class (only skills used by workflow)
 * └── application.properties (minimal configuration)
 * </pre>
 *
 * @author Wayang Team
 * @version 0.1.0
 * @since 2026-04-06
 */
public class AgentPackager {

    private static final String AGENT_MAIN_CLASS = "tech.kayys.wayang.agent.core.core.AgentClient";

    /**
     * Package agent JAR from workflow definition.
     *
     * @param workflowPath path to workflow YAML file
     * @param outputPath path for output JAR file
     * @param config packaging configuration
     * @return path to generated JAR
     * @throws IOException if packaging fails
     */
    public Path packageAgent(Path workflowPath, Path outputPath, PackageConfig config) throws IOException {
        // Analyze workflow to determine required components
        WorkflowAnalyzer analyzer = new WorkflowAnalyzer();
        DependencyReport report = analyzer.analyze(workflowPath);

        System.out.println("=== Agent Packaging Analysis ===");
        System.out.println(report);

        // Create output directory if needed
        Files.createDirectories(outputPath.getParent());

        // Create manifest
        Manifest manifest = createManifest(config.mainClass());

        // Generate JAR
        try (JarOutputStream jarOut = new JarOutputStream(Files.newOutputStream(outputPath), manifest)) {
            // Add application.properties
            addApplicationProperties(jarOut, report, config);

            // Add required classes (tree-shaking)
            if (config.optimize()) {
                addRequiredClasses(jarOut, report, config);
            } else {
                // Include all classes (no optimization)
                addAllClasses(jarOut, config);
            }

            // Add resources (SKILL.md files, etc.)
            addRequiredResources(jarOut, report, config);
        }

        System.out.println("✅ Agent JAR generated: " + outputPath);
        System.out.println("   Size: " + Files.size(outputPath) / (1024 * 1024) + " MB");

        return outputPath;
    }

    /**
     * Create JAR manifest with main class.
     */
    private Manifest createManifest(String mainClass) {
        Manifest manifest = new Manifest();
        Attributes attrs = manifest.getMainAttributes();
        attrs.put(Attributes.Name.MANIFEST_VERSION, "1.0");
        attrs.put(Attributes.Name.MAIN_CLASS, mainClass != null ? mainClass : AGENT_MAIN_CLASS);
        attrs.put(Attributes.Name.IMPLEMENTATION_TITLE, "Wayang-Gollek Agent");
        attrs.put(Attributes.Name.IMPLEMENTATION_VERSION, "1.0.0-SNAPSHOT");
        return manifest;
    }

    /**
     * Add application.properties with minimal configuration.
     */
    private void addApplicationProperties(JarOutputStream jarOut, DependencyReport report, PackageConfig config) throws IOException {
        jarOut.putNextEntry(new ZipEntry("application.properties"));

        StringBuilder props = new StringBuilder();
        props.append("# Wayang-Gollek Agent Configuration\n");
        props.append("# Generated by AgentPackager\n\n");

        // Backend configuration
        if (!report.requiredBackends().isEmpty()) {
            props.append("# Backend configuration\n");
            props.append("wayang.agent.inference.backend=").append(
                report.requiredBackends().iterator().next()
            ).append("\n");
            props.append("wayang.agent.workflow.backend=").append(
                report.requiredBackends().size() > 1 ?
                report.requiredBackends().stream().skip(1).findFirst().orElse("gamelan") : "gamelan"
            ).append("\n\n");
        }

        // Orchestrator configuration
        if (!report.requiredOrchestrators().isEmpty()) {
            props.append("# Orchestrator configuration\n");
            props.append("wayang.agent.default-strategy=").append(
                report.requiredOrchestrators().iterator().next()
            ).append("\n\n");
        }

        // Agent defaults
        props.append("# Agent defaults\n");
        props.append("wayang.agent.max-steps=").append(config.maxSteps()).append("\n");
        props.append("wayang.agent.timeout=").append(config.timeout()).append("\n");

        jarOut.write(props.toString().getBytes());
        jarOut.closeEntry();
    }

    /**
     * Add only required classes (tree-shaking optimization).
     */
    private void addRequiredClasses(JarOutputStream jarOut, DependencyReport report, PackageConfig config) throws IOException {
        // This is a simplified implementation
        // In production, this would:
        // 1. Parse class files to find dependencies
        // 2. Recursively add only reachable classes
        // 3. Exclude unused branches

        // For now, we add framework core + required executors
        addFrameworkCore(jarOut);

        // Add required executors based on workflow analysis
        for (String executor : report.requiredExecutors()) {
            addExecutorClasses(jarOut, executor);
        }

        // Add required orchestrators
        for (String orchestrator : report.requiredOrchestrators()) {
            addOrchestratorClasses(jarOut, orchestrator);
        }
    }

    /**
     * Add all classes (no optimization - simpler but larger JAR).
     */
    private void addAllClasses(JarOutputStream jarOut, PackageConfig config) throws IOException {
        // In production, this would scan classpath and add all classes
        // For now, this is a placeholder
        addFrameworkCore(jarOut);
    }

    /**
     * Add framework core classes (always required).
     */
    private void addFrameworkCore(JarOutputStream jarOut) throws IOException {
        // Core classes always needed:
        // - AgentClient
        // - AgentRequest/AgentResponse
        // - BackendRegistry
        // - InferenceBackend/WorkflowBackend interfaces

        // Placeholder: in production, these would be actual class files
        addPlaceholderClass(jarOut, "tech/kayys/gollek/agent/core/AgentClient.class");
        addPlaceholderClass(jarOut, "tech/kayys/wayang/agent/spi/InferenceBackend.class");
        addPlaceholderClass(jarOut, "tech/kayys/wayang/agent/spi/WorkflowBackend.class");
        addPlaceholderClass(jarOut, "tech/kayys/wayang/agent/spi/BackendRegistry.class");
    }

    /**
     * Add executor classes for specific executor type.
     */
    private void addExecutorClasses(JarOutputStream jarOut, String executorType) throws IOException {
        // Map executor type to class paths
        switch (executorType) {
            case "prompt-executor":
                addPlaceholderClass(jarOut, "tech/kayys/gollek/agent/prompt/PromptNodeExecutor.class");
                break;
            case "tool-executor":
                addPlaceholderClass(jarOut, "tech/kayys/gollek/agent/tools/ToolCallExecutor.class");
                break;
            case "rag-executor":
                addPlaceholderClass(jarOut, "tech/kayys/gollek/agent/rag/RAGExecutor.class");
                break;
            // Add more executor mappings...
        }
    }

    /**
     * Add orchestrator classes for specific orchestrator type.
     */
    private void addOrchestratorClasses(JarOutputStream jarOut, String orchestratorType) throws IOException {
        switch (orchestratorType) {
            case "react":
                addPlaceholderClass(jarOut, "tech/kayys/gollek/agent/orchestrator/ReActOrchestrator.class");
                break;
            case "plan-and-execute":
                addPlaceholderClass(jarOut, "tech/kayys/gollek/agent/orchestrator/PlanAndExecuteOrchestrator.class");
                break;
            case "reflexion":
                addPlaceholderClass(jarOut, "tech/kayys/gollek/agent/orchestrator/ReflexionOrchestrator.class");
                break;
            // Add more orchestrator mappings...
        }
    }

    /**
     * Add required resources (SKILL.md files, etc.).
     */
    private void addRequiredResources(JarOutputStream jarOut, DependencyReport report, PackageConfig config) throws IOException {
        // Add SKILL.md files for required skills
        for (String skill : report.requiredSkills()) {
            Path skillDir = config.skillsDir().resolve(skill);
            if (Files.exists(skillDir)) {
                addDirectory(jarOut, skillDir, "skills/" + skill + "/");
            }
        }
    }

    /**
     * Add placeholder class file (for demonstration).
     */
    private void addPlaceholderClass(JarOutputStream jarOut, String classPath) throws IOException {
        jarOut.putNextEntry(new ZipEntry(classPath));
        // Minimal valid class file (magic number + version + constant pool)
        jarOut.write(new byte[] {
            (byte) 0xCA, (byte) 0xFE, (byte) 0xBA, (byte) 0xBE,  // Magic
            0x00, 0x00, 0x00, 0x3D,  // Version 61 (Java 7)
            0x00, 0x01,  // Constant pool count
            0x00         // Placeholder content
        });
        jarOut.closeEntry();
    }

    /**
     * Add directory contents to JAR.
     */
    private void addDirectory(JarOutputStream jarOut, Path dirPath, String prefix) throws IOException {
        try (var stream = Files.walk(dirPath)) {
            stream.filter(Files::isRegularFile)
                .forEach(file -> {
                    try {
                        String entryName = prefix + dirPath.relativize(file).toString();
                        jarOut.putNextEntry(new ZipEntry(entryName));
                        Files.copy(file, jarOut);
                        jarOut.closeEntry();
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                });
        }
    }
}
