package tech.kayys.wayang.gollek.cli;

import tech.kayys.wayang.gollek.sdk.WayangGollekSdk;

import java.util.List;
import java.util.function.Supplier;

final class WayangCliRunGoldenFixtures {
    private static final Supplier<WayangGollekSdk> LIFECYCLE_SDK = ContractLifecycleSdk::new;
    private static final List<WayangCliGoldenFixtures.GoldenFixture> ALL = List.of(
            lifecycleSelfDescribing(
                    "run-preflight-json.golden",
                    "run",
                    "contract prompt",
                    "--workspace",
                    "/contract/workspace",
                    "--harness",
                    "--skill",
                    "repo",
                    "--preflight",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-preview-json.golden",
                    List.of("run-dry-json"),
                    "run",
                    "contract prompt",
                    "--system",
                    "contract system",
                    "--tenant",
                    "tenant-contract",
                    "--model",
                    "model-contract",
                    "--workflow",
                    "contract-workflow",
                    "--surface",
                    "coding-agent",
                    "--session",
                    "session-contract",
                    "--user",
                    "user-contract",
                    "--workspace",
                    "/contract/workspace",
                    "--harness",
                    "--skill",
                    "repo",
                    "--max-steps",
                    "7",
                    "--dry-run",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-spec-dry-json.golden",
                    "run",
                    "--spec",
                    "src/test/resources/run-specs/contract-run.properties",
                    "--dry-run",
                    "--json"),
            lifecycleSelfDescribing("run-result-json.golden", "run", "contract prompt", "--json"),
            lifecycleSelfDescribing(
                    "run-status-json.golden",
                    "run",
                    "status",
                    ContractLifecycleSdk.RUN_ID,
                    "--json"),
            lifecycleSelfDescribing(
                    "run-list-base-json.golden",
                    List.of("run-list-json"),
                    "run",
                    "list",
                    "--state",
                    "completed",
                    "--limit",
                    "10",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-list-json.golden",
                    List.of("run-list-filter-json"),
                    "run",
                    "list",
                    "--state",
                    "completed",
                    "--tenant",
                    "tenant-contract",
                    "--surface",
                    "assistant-agent",
                    "--limit",
                    "1",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-list-page-json.golden",
                    "run",
                    "list",
                    "--offset",
                    "10",
                    "--limit",
                    "10",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-list-profile-json.golden",
                    "run",
                    "list",
                    "--profile",
                    "assistant-agent",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-stats-json.golden",
                    "run",
                    "stats",
                    "--state",
                    "completed",
                    "--tenant",
                    "tenant-contract",
                    "--surface",
                    "assistant-agent",
                    "--limit",
                    "1",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-stats-profile-json.golden",
                    "run",
                    "stats",
                    "--profile",
                    "assistant-agent",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-events-base-json.golden",
                    List.of("run-events-json"),
                    "run",
                    "events",
                    ContractLifecycleSdk.RUN_ID,
                    "--json"),
            lifecycleSelfDescribing(
                    "run-events-json.golden",
                    List.of("run-events-filter-json"),
                    "run",
                    "events",
                    ContractLifecycleSdk.RUN_ID,
                    "--state",
                    "completed",
                    "--type",
                    "run.completed",
                    "--limit",
                    "5",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-events-cursor-json.golden",
                    "run",
                    "events",
                    ContractLifecycleSdk.RUN_ID,
                    "--after-sequence",
                    "10",
                    "--limit",
                    "20",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-events-stats-json.golden",
                    "run",
                    "events",
                    ContractLifecycleSdk.RUN_ID,
                    "--stats",
                    "--state",
                    "completed",
                    "--type",
                    "run.completed",
                    "--limit",
                    "5",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-events-follow-base-json.golden",
                    List.of("run-events-follow-json"),
                    "run",
                    "events",
                    ContractLifecycleSdk.RUN_ID,
                    "--follow",
                    "--max-polls",
                    "3",
                    "--poll-millis",
                    "1",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-events-follow-json.golden",
                    List.of("run-events-follow-result-json"),
                    "run",
                    "events",
                    ContractLifecycleSdk.RUN_ID,
                    "--follow",
                    "--follow-result",
                    "--state",
                    "completed",
                    "--type",
                    "run.completed",
                    "--limit",
                    "5",
                    "--max-polls",
                    "3",
                    "--poll-millis",
                    "1",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-events-follow-result-only-json.golden",
                    "run",
                    "events",
                    ContractLifecycleSdk.RUN_ID,
                    "--follow",
                    "--follow-result-only",
                    "--state",
                    "completed",
                    "--type",
                    "run.completed",
                    "--limit",
                    "5",
                    "--max-polls",
                    "3",
                    "--poll-millis",
                    "1",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-events-follow-result-only-stats-json.golden",
                    "run",
                    "events",
                    ContractLifecycleSdk.RUN_ID,
                    "--follow",
                    "--follow-result-only",
                    "--stats",
                    "--state",
                    "completed",
                    "--type",
                    "run.completed",
                    "--limit",
                    "5",
                    "--max-polls",
                    "3",
                    "--poll-millis",
                    "1",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-inspect-json.golden",
                    "run",
                    "inspect",
                    ContractLifecycleSdk.RUN_ID,
                    "--state",
                    "completed",
                    "--type",
                    "run.completed",
                    "--limit",
                    "5",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-wait-json.golden",
                    "run",
                    "wait",
                    ContractLifecycleSdk.RUN_ID,
                    "--timeout-seconds",
                    "0",
                    "--poll-millis",
                    "1",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-cancel-json.golden",
                    1,
                    "run",
                    "cancel",
                    ContractLifecycleSdk.RUN_ID,
                    "--reason",
                    "contract stop",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-store-json.golden",
                    "run",
                    "store",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-store-verify-json.golden",
                    "run",
                    "store",
                    "--verify",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-store-compact-dry-run-json.golden",
                    "run",
                    "store",
                    "--compact",
                    "--dry-run",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-store-compact-apply-json.golden",
                    "run",
                    "store",
                    "--compact",
                    "--apply",
                    "--json"),
            lifecycleSelfDescribing(
                    "run-forget-json.golden",
                    "run",
                    "forget",
                    ContractLifecycleSdk.RUN_ID,
                    "--json"));

    private WayangCliRunGoldenFixtures() {
    }

    static List<WayangCliGoldenFixtures.GoldenFixture> all() {
        return ALL;
    }

    private static WayangCliGoldenFixtures.GoldenFixture lifecycleSelfDescribing(String name, String... args) {
        return lifecycleSelfDescribing(name, 0, args);
    }

    private static WayangCliGoldenFixtures.GoldenFixture lifecycleSelfDescribing(
            String name,
            List<String> commandIds,
            String... args) {
        return lifecycleSelfDescribing(name, commandIds, 0, args);
    }

    private static WayangCliGoldenFixtures.GoldenFixture lifecycleSelfDescribing(
            String name,
            int expectedExitCode,
            String... args) {
        return new WayangCliGoldenFixtures.GoldenFixture(
                name,
                "contract-lifecycle",
                LIFECYCLE_SDK,
                List.of(args),
                expectedExitCode,
                WayangCliGoldenFixtures.SchemaMode.SELF_DESCRIBING,
                null);
    }

    private static WayangCliGoldenFixtures.GoldenFixture lifecycleSelfDescribing(
            String name,
            List<String> commandIds,
            int expectedExitCode,
            String... args) {
        return new WayangCliGoldenFixtures.GoldenFixture(
                name,
                "contract-lifecycle",
                LIFECYCLE_SDK,
                List.of(args),
                commandIds,
                expectedExitCode,
                WayangCliGoldenFixtures.SchemaMode.SELF_DESCRIBING,
                null);
    }
}
