#!/usr/bin/env bash
#
# Build & install the Wayang‑Gollek CLI locally.
# -------------------------------------------------
#  • Works on macOS (zsh/bash) – tested on macOS 14.
#  • No external env files required.
#  • Installs the built binary to $HOME/.local/bin (default) or
#    a custom directory via the –install-dir flag.
#  • Uses Gradle Wrapper that ships with the repo.
# -------------------------------------------------

set -euo pipefail

# ---------- Configuration ----------
DEFAULT_INSTALL_DIR="${HOME}/.local/bin"
INSTALL_DIR="${DEFAULT_INSTALL_DIR}"   # can be overridden via CLI
GRADLE_WRAPPER="./gradlew"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------- Helper functions ----------
log()   { printf '%b\n' "${*}" ; }
error() { log "\e[31mERROR:\e[0m ${*}" >&2 ; }
info()  { log "\e[34mINFO:\e[0m ${*}" ; }

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Options:
  -h, --help            Show this help.
  -i, --install-dir DIR  Directory where the CLI binary will be placed.
                         Defaults to $DEFAULT_INSTALL_DIR
EOF
  exit 0
}

# ---------- Parse arguments ----------
while (( "$#" )); do
  case "$1" in
    -h|--help) usage ;;
    -i|--install-dir)
      INSTALL_DIR="${2:?missing argument for $1}"
      shift 2
      ;;
    *) error "Unknown option: $1"; usage ;;
  esac
done

# ---------- Ensure install dir exists ----------
mkdir -p "$INSTALL_DIR"

# ---------- Build the CLI ----------
info "Building Wayang‑Gollek CLI …"
cd "$PROJECT_ROOT/cli/wayang-gollek-cli"
# The CLI is a Maven project
"$PROJECT_ROOT/mvnw" clean package -DskipTests

# Find the built JAR (the shade plugin creates a fat jar, usually overriding the main one)
JAR_PATH=$(find target -name "wayang-gollek-cli-*.jar" | grep -v original | head -n 1 || true)

if [[ -z "$JAR_PATH" ]]; then
  # Fallback: some projects produce a plain JAR without `-all`
  JAR_PATH=$(find target -name "*.jar" -print -quit || true)
fi

if [[ -z "$JAR_PATH" ]]; then
  error "Could not locate built JAR – the Gradle build may have failed."
  exit 1
fi

info "Built JAR: $JAR_PATH"

# ---------- Create an executable wrapper ----------
# The CLI is a Java program. We ship a tiny Bash wrapper that
# invokes `java -jar` with the correct classpath.
WRAPPER_PATH="${INSTALL_DIR}/wayang-gollek"
cat > "$WRAPPER_PATH" <<'EOS'
#!/usr/bin/env bash
# Wrapper for Wayang‑Gollek CLI
# This file is auto‑generated by build-and-install-wayang-gollek.sh

# Resolve the location of the JAR relative to the wrapper.
# ($0 may be a symlink, so we resolve it.)
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
JAR_PATH="${SCRIPT_DIR}/share/wayang-gollek-cli.jar"

exec java \\
  --add-modules jdk.incubator.vector \\
  -Djava.util.logging.manager=org.jboss.logmanager.LogManager \\
  -jar "$JAR_PATH" "$@"
EOS

chmod +x "$WRAPPER_PATH"

# ---------- Install the JAR alongside the wrapper ----------
# We place the JAR in a `share/` sub‑directory next to the binary.
SHARE_DIR="${INSTALL_DIR}/share"
mkdir -p "$SHARE_DIR"
cp "$JAR_PATH" "${SHARE_DIR}/wayang-gollek-cli.jar"

info "Installed CLI wrapper to: $WRAPPER_PATH"
info "Installed JAR to: ${SHARE_DIR}/wayang-gollek-cli.jar"
info "Add ${INSTALL_DIR} to your PATH if it is not already there:"
info "  export PATH=\"${INSTALL_DIR}:\$PATH\""

# ---------- Post‑install sanity check ----------
if command -v wayang-gollek >/dev/null 2>&1; then
  info "✅ Wayang‑Gollek CLI is ready! Try running:"
  info "    wayang-gollek --help"
else
  error "Installation succeeded but the binary is not on your PATH."
  error "Add the install directory to PATH or invoke it directly:"
  error "    ${WRAPPER_PATH} --help"
fi