# Quarkus Native Image Configuration for Wayang CLI
quarkus.native.additional-build-args=--enable-native-access=ALL-UNNAMED,-H:+JNI,-Dorg.jline.terminal.jansi=false,-Dorg.jline.terminal.jna=false
quarkus.log.level=WARN
quarkus.cache.redis.model-manifests.value-type=java.lang.String
quarkus.arc.exclude-types=tech.kayys.gollek.safetensor.config.SafetensorConfigProducer,tech.kayys.gollek.sdk.local.LocalGollekSdkProvider,tech.kayys.gollek.engine.registry.GollekProviderRegistry,tech.kayys.gollek.safetensor.engine.sdk.SafetensorGollekSdk,tech.kayys.gollek.engine.module.SystemModule
