package tech.kayys.wayang.rag.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;

/**
 * Schema DTO for RAG operation performance and quality metrics.
 */
public class RagMetricsSchema {

    @JsonProperty("totalDurationMs")
    @JsonPropertyDescription("Total wall-clock duration of the RAG operation in milliseconds.")
    private Long totalDurationMs;

    @JsonProperty("documentsRetrieved")
    @JsonPropertyDescription("Number of documents retrieved from the vector store.")
    private Integer documentsRetrieved;

    @JsonProperty("tokensGenerated")
    @JsonPropertyDescription("Number of tokens generated by the LLM.")
    private Integer tokensGenerated;

    @JsonProperty("averageSimilarityScore")
    @JsonPropertyDescription("Average cosine similarity score across all retrieved documents.")
    private Float averageSimilarityScore;

    @JsonProperty("rerankedResults")
    @JsonPropertyDescription("Number of results that were reranked.")
    private Integer rerankedResults;

    @JsonProperty("hallucinationScore")
    @JsonPropertyDescription("Hallucination score (0 = no hallucination detected).")
    private Integer hallucinationScore;

    @JsonProperty("groundingVerified")
    @JsonPropertyDescription("Whether the response was verified against the retrieved context for grounding.")
    private Boolean groundingVerified;

    public RagMetricsSchema() {
    }

    public Long getTotalDurationMs() {
        return totalDurationMs;
    }

    public void setTotalDurationMs(Long totalDurationMs) {
        this.totalDurationMs = totalDurationMs;
    }

    public Integer getDocumentsRetrieved() {
        return documentsRetrieved;
    }

    public void setDocumentsRetrieved(Integer documentsRetrieved) {
        this.documentsRetrieved = documentsRetrieved;
    }

    public Integer getTokensGenerated() {
        return tokensGenerated;
    }

    public void setTokensGenerated(Integer tokensGenerated) {
        this.tokensGenerated = tokensGenerated;
    }

    public Float getAverageSimilarityScore() {
        return averageSimilarityScore;
    }

    public void setAverageSimilarityScore(Float averageSimilarityScore) {
        this.averageSimilarityScore = averageSimilarityScore;
    }

    public Integer getRerankedResults() {
        return rerankedResults;
    }

    public void setRerankedResults(Integer rerankedResults) {
        this.rerankedResults = rerankedResults;
    }

    public Integer getHallucinationScore() {
        return hallucinationScore;
    }

    public void setHallucinationScore(Integer hallucinationScore) {
        this.hallucinationScore = hallucinationScore;
    }

    public Boolean getGroundingVerified() {
        return groundingVerified;
    }

    public void setGroundingVerified(Boolean groundingVerified) {
        this.groundingVerified = groundingVerified;
    }
}
