name=wayang-gollek-extension
artifactId=wayang-gollek-quarkus-extension-deployment
version=1.0.0-SNAPSHOT
short-name=wayang-gollek
description=Wayang integration for Gollek (quarkus extension template)
