#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
WAYANG_HOME="${WAYANG_HOME:-$HOME/.wayang}"
BUNDLED_WAYANG_HOME="${BUNDLE_ROOT}/.wayang"

if [ -d "$BUNDLED_WAYANG_HOME" ] && [ "$BUNDLED_WAYANG_HOME" != "$WAYANG_HOME" ]; then
  mkdir -p "$WAYANG_HOME"
  tar -C "$BUNDLED_WAYANG_HOME" -cf - . | tar -C "$WAYANG_HOME" -xf -
fi

WAYANG_CONFIG_DIR="${WAYANG_CONFIG_DIR:-$WAYANG_HOME/config}"
WAYANG_LOG_DIR="${WAYANG_LOG_DIR:-$WAYANG_HOME/logs}"
WAYANG_SERVER_LOG_DIR="${WAYANG_SERVER_LOG_DIR:-$WAYANG_LOG_DIR/server}"
WAYANG_LOG_FILE_PATH="${WAYANG_LOG_FILE_PATH:-$WAYANG_SERVER_LOG_DIR/server.log}"
WAYANG_PLUGINS_DIR="${WAYANG_PLUGINS_DIR:-$WAYANG_HOME/plugins}"
WAYANG_SECRETS_DIR="${WAYANG_SECRETS_DIR:-$WAYANG_HOME/secrets}"
WAYANG_MODELS_DIR="${WAYANG_MODELS_DIR:-$WAYANG_HOME/models}"
WAYANG_MCP_DIR="${WAYANG_MCP_DIR:-$WAYANG_HOME/mcp}"
WAYANG_RUN_DIR="${WAYANG_RUN_DIR:-$WAYANG_HOME/run}"
WAYANG_VECTOR_DIR="${WAYANG_VECTOR_DIR:-$WAYANG_HOME/vector}"
WAYANG_GOLLEK_HOME="${WAYANG_GOLLEK_HOME:-$WAYANG_HOME/gollek}"
LEGACY_GOLLEK_HOME="${GOLLEK_HOME:-$HOME/.gollek}"

if mkdir -p "$WAYANG_GOLLEK_HOME" 2>/dev/null; then
  GOLLEK_HOME="$WAYANG_GOLLEK_HOME"
else
  mkdir -p "$LEGACY_GOLLEK_HOME"
  GOLLEK_HOME="$LEGACY_GOLLEK_HOME"
fi

WAYANG_GOLLEK_MODELS_DIR="${WAYANG_GOLLEK_MODELS_DIR:-$GOLLEK_HOME/models}"
WAYANG_GOLLEK_STORAGE_DIR="${WAYANG_GOLLEK_STORAGE_DIR:-$GOLLEK_HOME/storage}"

mkdir -p \
  "$WAYANG_CONFIG_DIR" \
  "$WAYANG_SERVER_LOG_DIR" \
  "$WAYANG_PLUGINS_DIR" \
  "$WAYANG_SECRETS_DIR" \
  "$WAYANG_MODELS_DIR" \
  "$WAYANG_MCP_DIR" \
  "$WAYANG_RUN_DIR" \
  "$WAYANG_VECTOR_DIR" \
  "$WAYANG_GOLLEK_MODELS_DIR" \
  "$WAYANG_GOLLEK_STORAGE_DIR"

WAYANG_EXECUTABLE="${WAYANG_EXECUTABLE:-$WAYANG_HOME/bin/wayang}"
if [ ! -x "$WAYANG_EXECUTABLE" ]; then
  chmod +x "$WAYANG_EXECUTABLE" 2>/dev/null || true
fi
if [ ! -x "$WAYANG_EXECUTABLE" ]; then
  echo "Wayang executable not found or not executable: $WAYANG_EXECUTABLE" >&2
  exit 1
fi

SYSTEMD_USER_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
SERVICE_FILE="$SYSTEMD_USER_DIR/wayang.service"
mkdir -p "$SYSTEMD_USER_DIR"

cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Wayang service
After=network-online.target

[Service]
Type=simple
ExecStart=$WAYANG_EXECUTABLE
Restart=on-failure
RestartSec=5
Environment=WAYANG_HOME=$WAYANG_HOME
Environment=WAYANG_CONFIG_DIR=$WAYANG_CONFIG_DIR
Environment=WAYANG_LOG_DIR=$WAYANG_LOG_DIR
Environment=WAYANG_SERVER_LOG_DIR=$WAYANG_SERVER_LOG_DIR
Environment=WAYANG_LOG_FILE_PATH=$WAYANG_LOG_FILE_PATH
Environment=WAYANG_PLUGINS_DIR=$WAYANG_PLUGINS_DIR
Environment=WAYANG_SECRETS_DIR=$WAYANG_SECRETS_DIR
Environment=WAYANG_MODELS_DIR=$WAYANG_MODELS_DIR
Environment=WAYANG_MCP_DIR=$WAYANG_MCP_DIR
Environment=WAYANG_RUN_DIR=$WAYANG_RUN_DIR
Environment=WAYANG_VECTOR_DIR=$WAYANG_VECTOR_DIR
Environment=WAYANG_GOLLEK_HOME=$WAYANG_GOLLEK_HOME
Environment=GOLLEK_HOME=$GOLLEK_HOME
Environment=WAYANG_GOLLEK_MODELS_DIR=$WAYANG_GOLLEK_MODELS_DIR
Environment=WAYANG_GOLLEK_STORAGE_DIR=$WAYANG_GOLLEK_STORAGE_DIR
WorkingDirectory=$WAYANG_HOME

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now wayang.service
echo "Installed Wayang systemd user service at $SERVICE_FILE"
